### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by doorleyr** [CityScope/CS_Andorra_RNC#1]
Since this is specific to Andorra, I think the naming convention is CSL_Andorra... 
@agrignard  do you agree?

**Comment by RELNO** [comment]
This is true to be specific for Andorra [now], but in the long run this should become a tool for other places. Also, to me having one CSL per country is healthy convention, as it serves as on stop shop for collaborators.

**Comment by agrignard** [comment]
Yep I don't know exactly what to say here. It is not too far to be a global tool so CS_ makes sense but yes right now it could(should?) be CSL_Andorra

Also CS could mean what is develop by CS guys whereas CSL by the partner.

Maybe we need some clarification on this terminology.

**Comment by RELNO** [comment]
@agrignard @doorleyr  one easy solution is to name it CS_RNC. We are close with almost everything we do here to be generic for other data sets.

**Comment by agrignard** [comment]
Yep and to be more extreme it could be CS_MobilyData or something like that as what we are visualizing here is just some data about people. For andorra it comes from RNC but it can come from any other kind of spatial data (cuebiq,carto, etc etc).

**Comment by RELNO** [comment]
> it could be CS_MobilyData 


You probably meant mobile data? 
In any case, let's keep this in mind and keep the repo as is for now -- Andorra [Telecom, Turism, Actua, etc] are all part of this and this naming properly clarify it. 
As we move to reuse it with other places, we can make this more generic.

**Comment by RELNO** [comment]
Closing this for now. If we have another round on this project [new cities/ datasets] we'll consider more generic naming.
